#ifndef IDENTIFY_H_INCLUDED
#define IDENTIFY_H_INCLUDED

#define VOID	1
#define INT	    2
#define FLOAT	3
#define DOUBLE	4
#define IF	    5
#define ELSE	6
#define FOR	    7
#define DO	    8
#define WHILE	9
#define ID	    10
#define NUM	    11
#define PLUS	12
#define SUB	    13
#define MUL	    14
#define FEN	    15
#define DOU	    16
#define LS	    17
#define RS	    18
#define LL	    19
#define RL	    20
#define SMALL	21
#define ASSIGN	22
#define LARGE	23
#define LEAN	24
#define NOT	    25
#define LEQ	    26
#define SEQ	    27
#define NEQ	    28
#define EQ	    29
#define NOTE	30
#define PLUSD	31
#define SUBD	32
#define LEFT	33
#define RIGHT	34
#define PLEQ	35
#define SUEQ	36
#define MUEQ	37
#define DIEQ	38
#define YIN		39
#define PD		40
#define PC		41
#define PS		42
#define PLF		43
#define PER		44
#define RLEAN	45
#define NOTED	46
#endif // IDENTIFY_H_INCLUDED
